// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-yHMH12jnbF-i41ZJ8NHHvFaNteRyvIQ',
    appId: '1:1079928742403:web:9dcc2229cca51db36b2436',
    messagingSenderId: '1079928742403',
    projectId: 'sesac-hyeeun-jo',
    authDomain: 'sesac-hyeeun-jo.firebaseapp.com',
    storageBucket: 'sesac-hyeeun-jo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2WPcflaIRWlmyAIjESmGWPRFcRxXbkoo',
    appId: '1:1079928742403:android:4cb89f1b6cb8e20e6b2436',
    messagingSenderId: '1079928742403',
    projectId: 'sesac-hyeeun-jo',
    storageBucket: 'sesac-hyeeun-jo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTHlQ36AT2p7qF9b0SDNWJIZGNP7T8S-8',
    appId: '1:1079928742403:ios:77ff5f21cc843f226b2436',
    messagingSenderId: '1079928742403',
    projectId: 'sesac-hyeeun-jo',
    storageBucket: 'sesac-hyeeun-jo.firebasestorage.app',
    iosBundleId: 'com.example.moaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTHlQ36AT2p7qF9b0SDNWJIZGNP7T8S-8',
    appId: '1:1079928742403:ios:77ff5f21cc843f226b2436',
    messagingSenderId: '1079928742403',
    projectId: 'sesac-hyeeun-jo',
    storageBucket: 'sesac-hyeeun-jo.firebasestorage.app',
    iosBundleId: 'com.example.moaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-yHMH12jnbF-i41ZJ8NHHvFaNteRyvIQ',
    appId: '1:1079928742403:web:f0a637ca007acc106b2436',
    messagingSenderId: '1079928742403',
    projectId: 'sesac-hyeeun-jo',
    authDomain: 'sesac-hyeeun-jo.firebaseapp.com',
    storageBucket: 'sesac-hyeeun-jo.firebasestorage.app',
  );

}