// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Peiz-IPpikHsL1CeeYPCGjZyEKzppS8',
    appId: '1:678664566391:web:e4f972cb462c55e0507872',
    messagingSenderId: '678664566391',
    projectId: 'moaproject-1b718',
    authDomain: 'moaproject-1b718.firebaseapp.com',
    storageBucket: 'moaproject-1b718.firebasestorage.app',
    measurementId: 'G-WPPZZ9RZ9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2oQ1pqmXndKKXBNRtSoywJA0uctG3-54',
    appId: '1:678664566391:android:6261fa203c8930c8507872',
    messagingSenderId: '678664566391',
    projectId: 'moaproject-1b718',
    storageBucket: 'moaproject-1b718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEM0GQw1pSmwnk6UR-4YfGwV-JVvq0MzM',
    appId: '1:678664566391:ios:9231105a5744f407507872',
    messagingSenderId: '678664566391',
    projectId: 'moaproject-1b718',
    storageBucket: 'moaproject-1b718.firebasestorage.app',
    iosBundleId: 'com.example.moaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEM0GQw1pSmwnk6UR-4YfGwV-JVvq0MzM',
    appId: '1:678664566391:ios:9231105a5744f407507872',
    messagingSenderId: '678664566391',
    projectId: 'moaproject-1b718',
    storageBucket: 'moaproject-1b718.firebasestorage.app',
    iosBundleId: 'com.example.moaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Peiz-IPpikHsL1CeeYPCGjZyEKzppS8',
    appId: '1:678664566391:web:2c60dbc7277dd100507872',
    messagingSenderId: '678664566391',
    projectId: 'moaproject-1b718',
    authDomain: 'moaproject-1b718.firebaseapp.com',
    storageBucket: 'moaproject-1b718.firebasestorage.app',
    measurementId: 'G-P577CF8DFR',
  );
}
